name: Terraform Deployment Workflow  # Workflow Name

on:
  push:
    branches:
      - main  # Runs on push to the main branch

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest  # GitHub-hosted runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Login to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Set SSH Public Key
        run: |
          echo "SSH_PUBLIC_KEY=$(cat ~/.ssh/id_rsa.pub)" >> $GITHUB_ENV

      - name: Terraform Plan
        run: terraform plan -var "ssh_key=$SSH_PUBLIC_KEY"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var "ssh_key=$SSH_PUBLIC_KEY"
