name: Deploy to Azure VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Initialize Terraform
      run: terraform init
      working-directory: terraform

    - name: Apply Terraform
      run: terraform apply -auto-approve
      working-directory: terraform
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    - name: Extract Terraform Outputs (Public IP & SSH Key)
      run: |
        echo "VM_IP=$(terraform output -raw public_ip)" >> $GITHUB_ENV
        echo "PRIVATE_KEY='$(terraform output -raw private_key)" >> $GITHUB_ENV
      working-directory: terraform

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $VM_IP >> ~/.ssh/known_hosts

    - name: Deploy Application
      run: |
        scp -r * azureuser@$VM_IP:/home/azureuser/app
        ssh azureuser@$VM_IP "cd /home/azureuser/app && docker-compose up -d"
